### ISSUE TITLE
can't find the file palettes.json

### ISSUE THREAD

**Issue by gielk** [paolotremadio/homebridge-automation-lifx-colour-palettes#4]
Error: ENOENT: no such file or directory, open './palettes.json'

I have the file in the same location as Homebridge. But i looks like it can't find the file.

What do I do wrong?

I also tried ~/root/.homebridge/palettes.json
or just palettes.json

<img width="1697" alt="Screenshot 2020-10-26 at 16 15 57" src="https://user-images.githubusercontent.com/24224715/97190987-b0041680-17a6-11eb-966e-733cb86d9ad4.png">

**Comment by gielk** [comment]
Also i get this comment when starting homebridge

`The plugin "homebridge-automation-lifx-colour-palettes" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
`

**Comment by paolotremadio** [comment]
What command do you use to run homebridge?

**Comment by gielk** [comment]
> What command do you use to run homebridge?

sudo homebridge -I
I also used sudo homebridge but that made no difference.

**Comment by paolotremadio** [comment]
Try to `cd` the folder where the palette.json is and try to run it

**Comment by gielk** [comment]
> Try to `cd` the folder where the palette.json is and try to run it

Thanks!! That fixed it for me! Awesome work love the plugin!

**Comment by paolotremadio** [comment]
You’re welcome 😉
